apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-springboot-hello-qnbe
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-springboot-hello-qnbe
    app.kubernetes.io/part-of: accounting
  name: java-springboot-hello-qnbe
  namespace: burrzinga-tenant
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: java-springboot-app
    app.kubernetes.io/instance: java-springboot-hello-qnbe
status:
  loadBalancer: {}
